language: d

os:
  - linux
  - osx

d:
  - dmd-2.069.2
  - dmd-2.071.0
  
matrix:
  exclude:
    - os: osx
      d: dmd-2.069.2
  
script:
    - dub run :printdirs --compiler=${DC}
    - if [ `uname` = "Darwin" ]; then dub run :printdirs --combined --config=cocoa --compiler=${DC} ; fi

