language: d
matrix:
  include:
    - d: dmd
      os: linux
      env: CONFIG=default
    - d: dmd
      os: osx
      env: CONFIG=default
    - d: ldc
      os: linux
      env: CONFIG=default
    - d: ldc
      os: osx
      env: CONFIG=cocoa

script:
    - dub build --compiler=${DC} --config=${CONFIG}
    - dub --single examples/printdirs --compiler=${DC} --override-config=standardpaths/${CONFIG}
