
env:
  - CONFIG=default
  
matrix:
  include:
    - d: dmd-2.069.2
      os: linux
    - d: dmd-2.069.2
      os: osx
    - d: gdc-4.9.2
      os: linux
    - d: ldc-1.0.0
      os: linux
    - d: ldc-1.0.0
      os: osx
      env: CONFIG=cocoa
  
script:
    - dub build --compiler=${DC} --config=${CONFIG}
    - dub run :printdirs --compiler=${DC} --config=${CONFIG}
