language: d

os:
  - linux
  - osx

d:
  - dmd-2.071.0
  - dmd-2.069.2
  - gdc-4.9.2
  - ldc-0.15.1
  
matrix:
  exclude:
    - d: gdc-4.9.2
      os: osx
    - d: ldc-0.15.1
      os: osx
    - d: dmd-2.069.2
      os: osx
  
script:
    - dub build --compiler=${DC}
    - dub run :printdirs --compiler=${DC}
