language: d
matrix:
  include:
    - d: dmd-2.071.0
      os: linux
      env: CONFIG=default
    - d: dmd-2.071.0
      os: osx
      env: CONFIG=default
    - d: ldc-1.0.0
      os: linux
      env: CONFIG=default
    - d: ldc-1.0.0
      os: osx
      env: CONFIG=cocoa
  
script:
    - dub build --compiler=${DC} --config=${CONFIG}
    - dub run :printdirs --compiler=${DC} --config=${CONFIG}
