language: d
matrix:
    allow_failures:
        - d: gdc-4.8.2
        - d: ldc-0.14.0
    include:
        - d: dmd-2.066.1
        - d: dmd-2.065.0
        - d: gdc-4.8.2
        - d: ldc-0.15.1
        - d: ldc-0.14.0
script:
    - dub build standardpaths:printdirs --compiler=${DC}
    - dub build standardpaths:findexecutable --compiler=${DC}